lm-tools/choose-your-activities

- README.md
- app/views/partials/google-tag-manager.mustache
- test/integration/introduction.spec.js
- test/integration/unsorted-activities.spec.js
> Integrate with GTM

- test/integration/support/db-helper.js
- test/integration/unsorted-activities.spec.js
This is micro small change that will support tests for sorted activities. Those tests will require inserting many more rows into db. Having single method will be less noisy without promises everywhere.
> Refactor helper to insert multiple activities

- app/controllers/activity-view-model.js
- app/controllers/sorted-activities-controller.js
- app/views/sorted-activities.mustache
- test/common/page_objects/sorted-activities-page.js
- test/integration/sorted-activities.spec.js
Contains sorting of activities and styling the page. 
Excludes:
- Details link
- collapse buttons
> Display sorted activities per category

- app/views/sorted-activities.mustache
- This form element is completaly expandable
> Remove <form> from sorted activities list

- app/assets/stylesheets/style.scss
- gulpfile.js
- package.json
Required by show/hide buttons to display arrow icons
> Add font-awesome

- .eslintrc
- app/assets/js/_hide-show.js
- app/assets/js/main.js
- app/assets/stylesheets/style.scss
- app/locales/en.json
- app/views/sorted-activities.mustache
- test/common/page_objects/sorted-activities-page.js
- test/integration/sorted-activities.spec.js
- test/integration/support/test-data.js
- hide 3 categories on the bottom by default
- add show/hide button
> Hide activities for categories

- app/assets/stylesheets/style.scss
- app/views/sorted-activities.mustache
- Change cursor on sorted activities page to not be a pointer by default
Serves to address issue #29
> Sorted activity cursor

- app/views/re-sort-activities.mustache
@jessstubenbord please confirm this is cool
> Fix re-sort activity order

- app/assets/js/_slider.js
- app/assets/stylesheets/style.scss
- app/controllers/unsorted-activity-view-model.js
- app/views/unsorted-activities.mustache
> Change colour and clickability of a sorted activity

- app/assets/js/_slider.js
Change aims to address comments on #27 
@jessstubenbord please take a look and let me know.
> Slide activity full page width

- app/locales/en.json
Element `<a>` was not closed which produced invalid html structure
> Fix html for ACT-3 activity details

- app/views/activity-details.mustache
> Update details page back link to use gov.uk styles

- README.md
- gulpfile.js
- npm-shrinkwrap.json
- package.json
- scripts/url-checker.js
- scans `en.json` activity details content to find dead links
Output:
``` bash
choose-your-activities git:(html-checker) ✗ npm run check-content
> choose-your-activities@0.0.0 check-content /Users/lukaszkaniowski/lmt/choose-your-activities
> gulp check-content
[16:22:35] Using gulpfile ~/lmt/choose-your-activities/gulpfile.js
[16:22:35] Starting 'check-content'...
[16:22:37] Found broken links:
[16:22:37] {
"brokenLinksCount": 22,
"activities": [
{
"activity": "Try volunteering",
"brokenLinks": [
"https://www.ncvo.org.uk/ncvo-volunteering",
"https://www.do-it.org"
]
},
{
"activity": "Get some work experience",
"brokenLinks": [
"https://www.prospects.ac.uk/jobs-and-work-experience/work-experience-and-internships",
"https://www.myworldofwork.co.uk/getting-job/work-experience"
]
},
{ …
```
> Add npm check-content task to find dead links

- app/locales/en.json
- test/integration/support/test-data.js
- created on branch from PR #57
> Move "English and Math" activity to 10th position

- app/controllers/introduction-controller.js
- test/integration/entrypoints.spec.js
- test/integration/introduction.spec.js
> Use account id if passed in request to entrypoint

- app/controllers/activity-view-model.js
- app/controllers/unsorted-activities-controller.js
- app/locales/en.json
- app/views/sorted-activities.mustache
- app/views/unsorted-activities-all-sorted.mustache
- test/common/page_objects/sorted-activities-base-page.js
- test/common/page_objects/unsorted-activities-page.js
- test/integration/re-sort-activities.spec.js
- test/integration/sorted-activities.spec.js
- test/integration/support/db-helper.js
- test/integration/unsorted-activities.spec.js
Simplify design when all activities are already sorted
- add message on unsorted page
- remove navigation (sorted/unsorted) from all of the pages
> Improve UX after all activities sorted

- app/assets/stylesheets/style.scss
> Reduce margin for menu items

- scripts/url-checker.js
BrokenLinkChecker library doesn't seems to test nationalcareersservice correctly.
As a temp solution this url is excluded from blc and tested by bhttp library that is used internally by BLC.
> Exclude error url from blc check and test it seperataly

- db/reports.js
- scripts/fetch-metrics
- test/unit/reports.spec.js
+ Name change to activities to provide clarity
> Metric access script

- app/controllers/activity-details-controller.js
- app/controllers/categorise-activity-controller.js
- app/locales/en.json
- app/middleware/error-handler.js
- app/validators/activity-details-validator.js
- app/validators/categorise-activity-validator.js
- bin/www
- npm-shrinkwrap.json
- package.json
- test/integration/activity-details.spec.js
- test/integration/categorise-activity.spec.js
- test/integration/support/integrationSpecHelper.js
Validate activityId on:
* categorize page 
* activity details page
Validation is done with help of those libraries:
* [joi](https://github.com/hapijs/joi) - schema definition framework
* [celebrate](https://github.com/continuationlabs/celebrate) - express middleware to handle joi validation errors
In order to test `POST` requests with incorrect parameters [supertest](https://github.com/visionmedia/supertest) is used
> Validate activity id

- app/validators/activity-details-validator.js
- app/validators/categorise-activity-validator.js
- test/integration/categorise-activity.spec.js
- check category against know categories
- category is required
- update activity id to be required
> Validate category

- app/locales/en.json
- test/integration/activity-details.spec.js
- test/integration/categorise-activity.spec.js
It is believed that this copy is better
> Update copy for 400 error

- Dockerfile
- README.md
- npm-shrinkwrap.json
- package-lock.json
- package.json
Security vulnerability patched into 6.11.1
https://nodesource.com/blog/node-js-security-release-summary-july-2017
> security vulnerability in <6.11.1

- scripts/url-checker.js
30 seconds timeout when link is not responding
> Add timeout to url checker

- scripts/url-checker.js
Aws seems to throtle outgoing http calls. This should fix problems with timout.
> Check urls in sequence

- app/assets/stylesheets/style.scss
- app/controllers/categorise-activity-controller.js
- app/controllers/category-mapping.js
- app/controllers/chosen-activities-controller.js
- app/validators/categorise-activity-validator.js
- app/views/categorise-activity-a.mustache
- app/views/categorise-activity-b.mustache
- app/views/chosen-activities.mustache
- package-lock.json
- test/common/page_objects/chosen-activities-page.js
- test/integration/activities.spec.js
- test/integration/chosen-activities.spec.js
- test/integration/sorted-activities.spec.js
- test/integration/support/db-helper.js
Adding change links to allow the user to re-categorise an activity from the chosen activities page.
> Chosen activities change links

- .gitignore
- package.json
- test/screenshots/.gitignore
Persisting the screenshots directory and clearing all screenshots on every test run.
> Managing screenshots for test failures
